// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xozvcfsxoyrgfaeznqtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvenZjZnN4b3lyZ2ZhZXpucXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTU4NTYsImV4cCI6MjA1ODkzMTg1Nn0.59mZkJdUp7KojR027B1bsBHnLujXPsV5aen3WghnK4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);